### ISSUE TITLE
Possible to include Wistia videos?

### ISSUE THREAD

**Issue by michaelkoper** [froala/wysiwyg-editor#1001]
Hi,

I can't find a way to include Wistia videos. I guess it isn't supported? They do require some injection of javascript so I guess it is tricky.

http://wistia.com/doc/embedding

Thanks

**Comment by stefanneculai** [comment]
You should change the `$.FroalaEditor.VIDEO_PROVIDERS` object and add Wistia.

**Comment by Taeon** [comment]
For anyone looking to add Wistia support, here's a snippet -- not pretty but it works

```javascript
$.FroalaEditor.VIDEO_PROVIDERS.push(
	{
		html:'{url}',
		provider:'wistia',
		test_regex:/^.*wistia.com\/medias\/.*/,
		url_regex:/^.*wistia.com\/medias\/(.*)$/,
		url_text:'<script src="//fast.wistia.com/embed/medias/$1.jsonp" async></script><script src="//fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_embed wistia_async_$1" style="height:349px;width:620px">&nbsp;</div>'
	}
);
```
...and here's some CSS (obviously requires FontAwesome):

```css
body.fr-video{
	border: 1px solid #999;
	background-color: #eee;
	width: 100%;
	display: block;
	min-height: 150px;
	border-radius: 3px;
	position: relative;
}
body .fr-video:after{
	width: 20px;
	height: 20px;
	content: '';
	font-family: FontAwesome;
	font-size: 14px;
	color: #999;
	top: 50%;
	left: 50%;
	position: absolute;
	transform: translateX(-50%) translateY(-50%);
}
```
