### ISSUE TITLE
Unknown break button

### ISSUE THREAD

**Issue by Dielz98** [froala/wysiwyg-editor#1089]
I don't setup anything but this + button always show up

![screen shot 2016-02-25 at 9 51 34 pm](https://cloud.githubusercontent.com/assets/17416861/13322834/eaec50b6-dc08-11e5-9cdf-aada8199a0b9.jpg)

It never showing in the documentation. What is it? How to get rid it off?

**Comment by stefanneculai** [comment]
It's a plugin called quick_insert. Just don't include it if you don't want to use it. :smile:

**Comment by Dielz98** [comment]
I like the idea but it often disappear before I reach that button made user confuse, especially when I use inline mode

**Comment by stefanneculai** [comment]
This problem is fixed on master and it doesn't disaapear anymore.

**Comment by Dielz98** [comment]
How you fixed it?

I fix it by changing css become:
```css
.fr-quick-insert {
    position: fixed;
    z-index: 9998;
    white-space: nowrap;
    padding-right: 1px;
    margin-left: -1px
}
```
