### ISSUE TITLE
Easier way have simplified styles / remove material design in popups, etc.

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#1261]
This is probably more feedback than a specific request exactly, but I'm still working on the v1 -> v2 upgrade in our app and one of the most frustrating changes in the Material Design look. Most of the basics of the editor look fine / universally applicable or are easy to customize. However the popups (Insert/edit Link, Insert Image) are especially opinionated and don't match many websites (e.g. look very out of place in a Bootstrap site). Additionally, they are hard to override to restore a simpler look and feel to, and the markup is bad (e.g. uses a `<span>` instead of a `<label>` for the "text" label as shown below)

Some styles have been tweaked, but this is close to what the popovers look like by default in my Bootstrap 2 app. Looks bad and takes a lot of custom CSS to make good/normal looking.
<img width="331" alt="screenshot 2016-05-13 22 06 07" src="https://cloud.githubusercontent.com/assets/97612/15266354/e8e03c84-1956-11e6-99e7-91cd3dd2acea.png">

It would be so much better if the markup was better and there was a separate but optional theme file introducing the material design parts.

**Comment by stefanneculai** [comment]
Last commit changes it to use `label` instead of `span`. Overriding it is not actually as hard. The following CSS restores it very close to what Bootstrap looks like.

```css
.fr-popup .fr-input-line input[type="text"], .fr-popup .fr-input-line textarea {
  border: solid 1px #CCC;
  padding: 5px;
  margin: 0;
}

.fr-popup .fr-input-line input[type="text"]:focus, .fr-popup .fr-input-line textarea:focus {
  border: solid 1px #1e88e5;
}

.fr-popup .fr-input-line {
  padding: 15px 0;
}

.fr-popup .fr-input-line input + label, .fr-popup .fr-input-line textarea + label {
  color: #000;
  display: block;
  font-size: 12px;
  font-weight: bold;
}
```
