### ISSUE TITLE
alignment is only applied to text but not list

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2473]
list with numbers or symbol should move with text on alignment change.
 
please check attached video.

[AlignmentonList.zip](https://github.com/froala/wysiwyg-editor/files/1614111/AlignmentonList.zip)

**Comment by stefanneculai** [comment]
We're not going to add it by default. However, if you would like to achieve this, please add the following:

```css
.fr-view ul, .fr-view ol {
  list-style-position: inside;
}
```
