### ISSUE TITLE
Is there a way to specify the container for the toolbar button options?

### ISSUE THREAD

**Issue by wrporter** [froala/wysiwyg-editor#2652]
`toolbarButtonsMD`, etc. base their changes on the device or window size. The editor may not always expand from the edges of the browser. Is there a way to specify that `toolbarButtonsMD`, etc. go off of the width of the container rather than the width of the browser window?

**Comment by stefanneculai** [comment]
Yes, just change the following. It's LESS code.

```LESS
// Screen sizes.
@screen-xs: 480px;
@screen-sm: 768px;
@screen-md: 992px;
@screen-lg: 1200px;
@screen-xs-max: (@screen-sm - 1);
@screen-sm-max: (@screen-md - 1);
@screen-md-max: (@screen-lg - 1);
@screen-lg-max: 'auto';

.fr-visibility-helper {
  display: none;
  margin-left: 0px !important;

  @media (min-width: @screen-sm) {
    margin-left: 1px !important;
  }

  @media (min-width: @screen-md) {
    margin-left: 2px !important;
  }

  @media (min-width: @screen-lg) {
    margin-left: 3px !important;
  }
}
```
