### ISSUE TITLE
Feature Request: Don't set table column widths

### ISSUE THREAD

**Issue by steffenweber** [froala/wysiwyg-editor#2716]
In a responsive design, it doesn't make much sense to let the user define table column widths (neither in pixels nor in percent). I think the browser should use its algorithm to automatically compute the column widths depending on their contents.

This can currently be achieved by setting "tableResizer" option to false and adding some ugly `!important` CSS rules:

```css
.fr-view table {
	width: auto !important;
}

.fr-element table td,
.fr-element table th {
	width: auto !important;
}
```

It would be nice if Froala supported a setting tableAutoSizing (or similar) where it doesn't set an explicit width for table cells (and the table itself).
