### ISSUE TITLE
Remove preset selection background color

### ISSUE THREAD

**Issue by theknet** [froala/wysiwyg-editor#3095]
##### Expected behavior.
When highlighting text in Safari, the text background is forced blue. However, you can change the highlight color within System Preferences. This means other text fields do not match the WYSIWYG editor.

##### Actual behavior.
Highlight color should be system defined

##### Steps to reproduce the problem.
View a Froala instance
Highlight text

##### OS.
macOS 10.14 Mojave

##### Browser.
Safari 12

**Comment by stefanneculai** [comment]
We have 2 CSS rules that specify how the selection should be: https://github.com/froala/wysiwyg-editor/blob/master/css/froala_editor.css#L159. They are added there so that there is a consistent highlight color in all browsers. If you'd like to use other colors, then you can override them:

```css
.fr-wrapper ::-moz-selection {
  background: auto !important;
  color: auto !important;
}
.fr-wrapper ::selection {
  background: auto !important;
  color: auto !important;
}
```
