### ISSUE TITLE
drop down should not exceeds froala editor

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#3207]
hi, 

Drop down should be limited inside froala editor.

![image](https://user-images.githubusercontent.com/25203829/50000780-6cda9900-ffbc-11e8-8f2a-ce27dd011caf.png)

**Comment by stefanneculai** [comment]
We don't consider it a bug - the dropdowns are not designed to be limited to the editor size. Actually, you can control them via CSS:
```css
.fr-command.fr-btn+.fr-dropdown-menu .fr-dropdown-wrapper .fr-dropdown-content,
.fr-command.fr-btn.fr-active+.fr-dropdown-menu .fr-dropdown-wrapper {
  max-height: 150px;
}
```
