### ISSUE TITLE
Table border invisible/transparent

### ISSUE THREAD

**Issue by ShanmugaPriyanV** [froala/wysiwyg-editor#3295]
I'm currently making a extensive template using froala which involves table and images can we have an option to make the cell border invisible/transparent.

Thanks

**Comment by stefanneculai** [comment]
Sure, you can use:
```CSS
.fr-view table td, .fr-view table th {
   border: none;
}
```

PS: We are using this channel mainly for bug reports. For tech questions, please use our [website contact form](https://www.froala.com/wysiwyg-editor/contact) and for feature suggestions: https://wysiwyg-editor-roadmap.froala.com/public.
