### ISSUE TITLE
Trivial bug in documentReady mode

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#3337]
##### Screen shot.

1. Selection area highlight box does not appear
![ws000005](https://user-images.githubusercontent.com/5575931/53783422-df706a80-3f54-11e9-8c30-66dae8f135e6.PNG)

embedly.css
```css
.fr-box .fr-embedly-resizer {
  position: absolute;
  z-index: 2; /* here (add) */
  border: solid 1px #1e88e5;
  display: none;
  user-select: none;
  -o-user-select: none;
  -moz-user-select: none;
  -khtml-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
}
```

2. The source code of codemirror is displayed in the center.
![ws000002](https://user-images.githubusercontent.com/5575931/53783431-e303f180-3f54-11e9-9a45-c2d18fe372c1.PNG)

froala_editor.css
```css
@media (min-width: 992px) {
  .fr-box.fr-document {
    min-width: 21cm;
  }
  .fr-box.fr-document .fr-wrapper {
    text-align: center; /* here */
    padding: 30px;
    min-width: 21cm;
    background: #EFEFEF;
  }
```

froala v2.9.3
