### ISSUE TITLE
Image click issues.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#3341]
##### Expected behavior.
![2019-03-10 22 27 10](https://user-images.githubusercontent.com/5575931/54085665-c9630f80-4383-11e9-980b-b78f5b7d7c0c.gif)

##### Actual behavior.
![2019-03-10 22 24 40](https://user-images.githubusercontent.com/5575931/54085675-dc75df80-4383-11e9-85ca-7287bb051fa0.gif)

v2.9.3

This issue is related to documentReady mode.
There is no problem until v2.9.1.
#3337

Regardless of documentReady setting, in order to solve this problem, you need to modify css as follows.

froala_editor.css
```css
.fr-element {
  background: transparent;
  position: relative;
/*  z-index: 2;  remove */
  -webkit-user-select: auto;
}

.fr-wrapper .fr-placeholder {
  position: absolute;
  font-size: 12px;
  color: #aaaaaa;
  z-index: -1; /* change from 1 to -1 */
  display: none;
  top: 0;
  left: 0;
  right: 0;
  overflow: hidden;
}

```
froala_style.css
```css
.fr-view img {
  position: relative;
  max-width: 100%;
  z-index: 1; /* add */
}
```
image.css
```css
.fr-image-resizer {
  position: absolute;
  border: solid 1px #1e88e5;
  display: none;
  user-select: none;
  -o-user-select: none;
  -moz-user-select: none;
  -khtml-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
/*  z-index: 2;  remove */
}
```

ps
You do not need to add a z-index in `.fr-*-resizer.`
