### ISSUE TITLE
The Quick Insert button appears above the toolbar.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#3393]
![WS000001](https://user-images.githubusercontent.com/5575931/56344814-4ee6a480-61f9-11e9-9c0d-c6677e196f22.PNG)

![WS000000](https://user-images.githubusercontent.com/5575931/56344810-4b531d80-61f9-11e9-9248-90bd1a47f0f1.PNG)

```css
.fr-quick-insert {
  position: absolute;
  z-index: 2147483639; /* <- here */
  white-space: nowrap;
  padding-right: 5px;
  margin-left: -5px;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
}
```

 I think the value like `.fr-qi-helper` looks good.
