### ISSUE TITLE
useClasses does not follow CSS cascading like the browser.

### ISSUE THREAD

**Issue by dobromir-hristov** [froala/wysiwyg-editor#3673]
##### Expected behavior.
When using the `useClasses: false` property, you should see styles applied to the elements, according to the CSS cascading rules, with more specific rules overwriting the weaker ones.

##### Actual behavior.
Froala ignores more specific rules, if they have already been defined, in favor of top level ones, like `ol { padding: 0 }`

##### Steps to reproduce the problem.
If you have some sort of css reset or normalize rules on your page (which 90% of websites have), most often a `padding:0; margin:0` gets applied to some items, like `ol, ul`.

If you want to overwrite those using lets say Bulma and their `.content` class, which just re-adds some nice default styles so content looks normal, previously defined styles are never overwritten and added to the final output from Froala, even though the browser renders them properly. 

```css
ul, ol { padding: 0 } /* this gets applied as it should */

.content ol {
  padding-left: 10px; /* this never lands in the output */
}

.content .fr-view ol {
  padding-left: 20px; /* this will get applied */
}
```

Here is a codepen showing the issue. Call the `getContent` func in the console with the commented CSS rules and then without them, and monitor the output where the `ol` element is.

https://codepen.io/dobromir/pen/NWKELqJ?editors=1111

##### Editor version.
3.0.5 and 2.x

##### OS.
OSX Mojave

##### Browser.
Firefox Dev 70.0b1
