### ISSUE TITLE
The included image.scss, video.scss and popup.scss files contain badly formatted code

### ISSUE THREAD

**Issue by chrisdeeming** [froala/wysiwyg-editor#3878]
Both files contain a number of style values which are terminated with a comma rather than a semi-colon.

```scss
  &.fr-active {
    display: block,
  }
```

```scss
    &.fr-hnw {
      cursor: nw-resize,
    }

    &.fr-hne {
      cursor: ne-resize,
    }

    &.fr-hsw {
      cursor: sw-resize,
    }

    &.fr-hse {
      cursor: se-resize,
    }
```

We are overriding the code ourselves using the following:
```less
// Fix for broken CSS in image.scss/image.less
.fr-image-resizer
{
	&.fr-active
	{
		display: block;
	}

	.fr-handler
	{
		&.fr-hnw
		{
			cursor: nw-resize;
		}

		&.fr-hne
		{
			cursor: ne-resize;
		}

		&.fr-hsw
		{
			cursor: sw-resize;
		}

		&.fr-hse
		{
			cursor: se-resize;
		}
	}
}

// Fix for broken CSS in video.scss/video.less
.fr-box .fr-video-resizer
{
	&.fr-active
	{
		display: block;
	}

	.fr-handler
	{
		&.fr-hnw
		{
			cursor: nw-resize;
		}

		&.fr-hne
		{
			cursor: ne-resize;
		}

		&.fr-hsw
		{
			cursor: sw-resize;
		}

		&.fr-hse
		{
			cursor: se-resize;
		}
	}
}
```

Also please go back to including the Less source files.
