### ISSUE TITLE
Placeholder does not show up if a background colour is applied to fr-view

### ISSUE THREAD

**Issue by pomartel** [froala/wysiwyg-editor#3914]
The `fr-view` div appear on top of the placeholder div. This causes a problem when trying to apply a background colour to the editor like in this exemple: https://jsfiddle.net/rdu4gsfa/4/

I have to style the `fr-box` instead and apply a transparent background to the `fr-view` this way for this to work:

```scss
.fr-box {
  background: #DDD;
  .fr-view {
    // Transparent background otherwise the placeholder doesn't show
    background: transparent;
  }
}
```

It looks like the placeholder is `position: absolute` and falls underneath the edition box.
