### ISSUE TITLE
Does not work on iOS in Ionic framework

### ISSUE THREAD

**Issue by dennisharrison** [froala/wysiwyg-editor#433]
See:
https://github.com/froala/angular-froala/issues/8

**Comment by stefanneculai** [comment]
Please make a jsFiddle or provide a link where we can test.

**Comment by dennisharrison** [comment]
Fixed:

You need 
```css
.froala-box, .froala-box .froala-wrapper.f-basic {
    -webkit-user-select: text !important;
    -moz-user-select: text !important;
    -ms-user-select: text !important;
    user-select: text !important;
}
```

Ionic has user-select: none; on a lot of elements.
