### ISSUE TITLE
Froala 4.2.1: `font-family` is set to `undefined`

### ISSUE THREAD

**Issue by dcsaszar** [froala/wysiwyg-editor#4795]
Froala 4.2.1 overwrites the `font-family` defined by the container (both iframe and inline editors).
It also tries to overwrite the `font-size` but luckily fails b/c of invalid CSS.

After checking the code: As a workaround, these options can be set:
```js
{
  fontFamilyDefaultSelection: "Font Family",
  fontSizeDefaultSelection: "Font Size",
}
```

##### Expected behavior.

Element, body, descendants `font-family` (and `font-size`) styles are respected/inherited.

##### Actual behavior.

```css
{  font-size: undefinedundefined !important; font-family: undefined !important; }
```

##### Steps to reproduce the problem.

https://codepen.io/dcsaszar/pen/OJYzyBw
```css
body {
  font-family: cursive;
}
```
```html
<div id="froala">Foo</div>
```
```js
import * as FroalaEditor from "froala-editor";

const element = document.getElementById("froala");
new FroalaEditor(element, { toolbarInline: true });
```

##### Editor version.

**4.2.1**

(it works as expected up to 4.2.0)

##### OS.

macOS 14.5 (23F79)

##### Browser.
Chrome  125.0.6422.142
##### Recording.

<img width="1511" alt="image" src="https://github.com/froala/wysiwyg-editor/assets/986170/79a4e1a9-dd57-4cd4-abcb-d26d6b8d1392">
