### ISSUE TITLE
Popups get cutoff by bottom of window

### ISSUE THREAD

**Issue by cstefan** [froala/wysiwyg-editor#4829]
##### Expected behavior.
The Popup position is calculated so that it is 100% visible.

##### Actual behavior.
In SPA type application, no scrollable container, and the editor is placed at the bottom of the page, like for a messaging app, the Toolbar triggered Popups are cropped.

##### Steps to reproduce the problem.

[Demo](https://jsfiddle.net/px0143vk/)

Just place the editor at a fixed position at the bottom of the page like this.

``` css
#froala-editor { 
    position: fixed;
    height: 150px;
    bottom: 0;
    left: 0;
    right: 0;
}
```

##### Editor version.
Version 4.2.1

##### OS.
ALL

##### Browser.
ALL
##### Recording.
(A recording showing how to reproduce the problem)
<img width="824" alt="image" src="https://github.com/user-attachments/assets/ba76130d-b131-4aa2-a6ee-1256e15972a0">
