### ISSUE TITLE
Fixed menu style needed to paragraphFormat Plugin.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#838]
For example, if the declared in an external style applies to paragraphFormat menu.

```javascript
paragraphFormat: {
	H2: 'H2',
	H3: 'H3',
	H4: 'H4',
	H5: 'H5',
	H6: 'H6',
	DIV: 'DIV',
	P: 'P',
	PRE: 'PRE',
	N: 'NORMAL'
},
```

```css
p
{
	margin: 12px 0 !important;
	line-height: 1.6 !important;
	text-align:left;
	word-break: break-all;
	word-wrap: break-word;
}
```

![screen shot 2015-10-08 at 23 06 28](https://cloud.githubusercontent.com/assets/5575931/10369016/0a128f1e-6e13-11e5-894f-8e0116fbf850.png)

#### SOLUTION
I solved the problem by improving, as shown below.

```javascript
// paragraph_format.js
  // Register the font size command.
  $.FroalaEditor.RegisterCommand('paragraphFormat', {
...
c += '<li><' + val + ' style="padding: 0 !important; margin: 0 !important;"><a >...</a></' + val + '></li>';
...
```

![screen shot 2015-10-08 at 23 24 27](https://cloud.githubusercontent.com/assets/5575931/10369159/c787daea-6e13-11e5-8695-a8fac20d4af1.png)
