### ISSUE TITLE
Please check css3 pseudo-elements.

### ISSUE THREAD

**Issue by largeden** [froala/wysiwyg-editor#945]
image_manager.css
```css
.fr-modal .fr-modal-wrapper div.fr-scroller div.fr-image-list div.fr-image-container::first-child {
  margin-top: 10px;
}
```
https://developer.mozilla.org/en-US/docs/Web/CSS/%3Afirst-child

:first-child is not css3 pseudo-element.

**Comment by stefanneculai** [comment]
I believe you're meaning `::first-child`, right?

**Comment by largeden** [comment]
From what I have tested,
At least firefox, chrome is not in operation.


```css
.fr-modal .fr-modal-wrapper div.fr-scroller div.fr-image-list div.fr-image-container::first-child {
  margin-top: 10px;
}
```
![2015-11-29 9 32 39](https://cloud.githubusercontent.com/assets/5575931/11454761/cfa5e528-967c-11e5-9711-38036145ece0.png)


```css
.fr-modal .fr-modal-wrapper div.fr-scroller div.fr-image-list div.fr-image-container:first-child {
  margin-top: 10px;
}
```
![2015-11-29 9 33 49](https://cloud.githubusercontent.com/assets/5575931/11454763/d7896ca6-967c-11e5-9d20-5ac7c10b6fe2.png)
