### ISSUE TITLE
Enhancement: custom toolbar button CSS class

### ISSUE THREAD

**Issue by MisterFreeze** [froala/wysiwyg-editor#977]
Hi!

My goal is to have a toolbar that has some large buttons for cancel, save, undo, redo at the top of the toolbar, separated by a horizontal line from the other buttons. This works using the following code (not too important):
``` javascript
let getFroalaEditorDefaults = (attr, exclude=[]) => {
  let deflt = $.FroalaEditor.DEFAULTS[attr]
  for (let x of exclude) {
    let i = deflt.indexOf(x)
    if (i > 0) {
      deflt.splice(i, 1)
    }
  }
  return deflt
}
let editorOptions = {
  ...
  // add custom buttons
  toolbarButtons: ['save', 'cancel', 'undo', 'redo',  '-'].concat(getFroalaEditorDefaults('toolbarButtons', ['redo', 'undo'])),
  ...
}
```

with the following CSS:
```CSS
.fr-command.fr-btn i.fa-floppy-o,
.fr-command.fr-btn i.fa-close,
.fr-command.fr-btn i.fa-rotate-left,
.fr-command.fr-btn i.fa-rotate-right,
{
    font-size: 50px;
    width: 50px
  }
}
```

What I would find really useful in this case was the ability to add a user-defined CSS class to the top buttons in the `toolbarButtons` definition.

Is there a way to achieve this?

If not, I could think of the following syntax for adding a CSS class `my-custom-button` to a button:
```javascript
let editorOptions = {
  ...
  // add custom buttons
  toolbarButtons: ['save .my-custom-button', 'cancel .my-custom-button', 'undo .my-custom-button', 'redo .my-custom-button', '-'].concat(getFroalaEditorDefaults('toolbarButtons', ['redo', 'undo'])),
  ...
}
```

This would allow for the definition of a single CSS class that affects all those buttons:
```CSS
.fr-command.fr-btn i.my-custom-button
{
    font-size: 50px;
    width: 50px
  }
}
```

The button string could be parsed like so, assuming `command` to hold the value of each `tooblarButtons` array element on iteration:
```javascript
var classes = command.split(' ')
if (classes.length < 1)
  throw new Error ("command name cannot be empty")
command = classes.shift()
var css = []
for (var c of classes) {
  if (c.indexOf('.') == 0) {
    css.push(c.subst(0, c.length))
  }
}
// add class using jQuery
$(<BUTTON-SELECTOR>).addClass(css.join(' '))
```

Best regards,

Chris
